services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Gupalo\AuditLogBundle\Controller\:
        resource: '../../Controller/'
        tags: [ 'controller.service_arguments' ]

    Gupalo\AuditLogBundle\Repository\AuditLogRepository:
        autowire: true

    Gupalo\AuditLogBundle\EventSubscriber\ArchiveEventSubscriber:
        autowire: true

    Gupalo\AuditLogBundle\EventSubscriber\CreateEventSubscriber:
        autowire: true

    Gupalo\AuditLogBundle\EventSubscriber\ExportEventSubscriber:
        autowire: true

    Gupalo\AuditLogBundle\EventSubscriber\ListEventSubscriber:
        autowire: true

    Gupalo\AuditLogBundle\EventSubscriber\LoginSuccessEventSubscriber:
        autowire: true

    Gupalo\AuditLogBundle\EventSubscriber\RestoreEventSubscriber:
        autowire: true

    Gupalo\AuditLogBundle\EventSubscriber\ViewEventSubscriber:
        autowire: true
